### ISSUE TITLE
Connect without using localhost

### ISSUE THREAD

**Issue by AAFFTechnologies** [paulmelnikow/ObjCMongoDB#24]
Hello, 

Im trying to access mongo from an ios app on a real device, and I obviously cant use 127.0.0.1 to connect to mongo db. But it appears the only way to connect to the database IS by using 127.0.0.1 on a local machine. Has anybody used a non local ip to acess mongo? if so, how?

Thanks!

**Comment by paulmelnikow** [comment]
Please try searching or posting on Stack Overflow for ObjCMongoDB. I try to follow there, and there are many others who will see the question too.

Not an issue with the library, so closing.

**Comment by pvogel1967** [comment]
if you are on iOS 9, since the MongoDB connection isn't over SSL you need
to disable transport security in your plist file.

App Transport Security Settings > Allow Arbitrary Loads > YES

Peter+

On Sat, Mar 12, 2016 at 12:19 PM, Paul Melnikow <notifications@github.com>
wrote:

> Closed #24 <https://github.com/paulmelnikow/ObjCMongoDB/issues/24>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulmelnikow/ObjCMongoDB/issues/24#event-587525971>.
>



-- 
Director, Fixed Wing Flight Training
Santa Clara County Model Aircraft Skypark
Associate Vice President, Academy of Model Aeronautics District X
Treasurer, National Society of Radio Control Aerobatics (NSRCA)
